### ISSUE TITLE
unary not does not work?

### ISSUE THREAD

**Issue by rusefi** [dtitov/bracer#3]
"!" seems to be supported - it's included in
 private final String OPERATORS = "+-*/&|!";

but does it work?

    @Test
    public void testUnaryNot() throws Exception {
        bracerParser.parse("! false");
        Assert.assertEquals("1", bracerParser.evaluate());
    }

produces
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at com.autsia.bracer.BracerParser.evaluate(BracerParser.java:224)
	at com.autsia.bracer.BracerParser.evaluate(BracerParser.java:186)

similar
    @Test
    public void testUnaryNot() throws Exception {
        bracerParser.parse("!(false)");
        Assert.assertEquals("1", bracerParser.evaluate());
    }

java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at com.autsia.bracer.BracerParser.evaluate(BracerParser.java:224)
	at com.autsia.bracer.BracerParser.evaluate(BracerParser.java:186)

**Comment by dtitov** [comment]
Hey! Thanks for reporting an issue. I've fixed it in 7.1 version, check it out :)
